# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: image

  test:
    desc: go test
    cmds:
      - cmd: go test ./...

  build:
    desc: Build main
    cmds:
      - cmd: go build -o ./bin/authorizer github.com/myhops/authorizer/cmd/authorizer

  image:
    desc: Build image
    cmds:
      - podman build --tag authorizer --file docker/Dockerfile .

  push:
    desc: Push image
    deps:
      - image
    cmds:
      # - cmd: rm /tmp/authorizer.image.tar
      - cmd: podman save localhost/authorizer:latest > /tmp/authorizer.image.tar
      - cmd: crane push /tmp/authorizer.image.tar docker.io/peterzandbergen/authorizer:v0.0.3
      