# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: image

  test:
    desc: go test
    cmds:
      - cmd: go test ./...

  build:
    desc: Build main
    cmds:
      - cmd: go build -o main github.com/myhops/authorizer/cmd/authorizer

  image:
    desc: Build image
    cmds:
      - podman build --tag authorizer --file docker/Dockerfile .

  push:
    desc: Push image
    deps:
      - image
    cmds:
      - cmd: crane copy localhost/authorizer docker.io/peterzandbergen/authorizer:latest